package cloud.liyan.emailmanager.dao.persistence;

import cloud.liyan.emailmanager.dao.model.EmailTask;
import cloud.liyan.emailmanager.dao.model.EmailTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int countByExample(EmailTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int deleteByExample(EmailTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int insert(EmailTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int insertSelective(EmailTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    List<EmailTask> selectByExample(EmailTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    EmailTask selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int updateByExampleSelective(@Param("record") EmailTask record, @Param("example") EmailTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int updateByExample(@Param("record") EmailTask record, @Param("example") EmailTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int updateByPrimaryKeySelective(EmailTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email_task
     *
     * @mbggenerated Sat Sep 07 14:03:29 CST 2019
     */
    int updateByPrimaryKey(EmailTask record);

    int insertBatchSelective(List<EmailTask> records);

    int updateBatchByPrimaryKeySelective(List<EmailTask> records);
}